/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/api/v1/admin/accounts": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Create Account */
        readonly post: operations["create_account_api_v1_admin_accounts_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/admin/revisions/{revision_id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Admin Revision */
        readonly get: operations["admin_revision_api_v1_admin_revisions__revision_id__get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/admin/revisions/{revision_id}/approve": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Approve Revision */
        readonly post: operations["approve_revision_api_v1_admin_revisions__revision_id__approve_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/admin/revisions/{revision_id}/original": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Admin Original */
        readonly get: operations["admin_original_api_v1_admin_revisions__revision_id__original_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/admin/revisions/{revision_id}/retry": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Retry Revision */
        readonly post: operations["retry_revision_api_v1_admin_revisions__revision_id__retry_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/admin/revisions/{revision_id}/revoke": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Revoke Revision */
        readonly post: operations["revoke_revision_api_v1_admin_revisions__revision_id__revoke_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/admin/sources": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Admin Sources */
        readonly get: operations["admin_sources_api_v1_admin_sources_get"];
        readonly put?: never;
        /** Upload Source */
        readonly post: operations["upload_source_api_v1_admin_sources_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/auth/login": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Login */
        readonly post: operations["login_api_v1_auth_login_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/auth/logout": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Logout */
        readonly post: operations["logout_api_v1_auth_logout_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/auth/me": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Me */
        readonly get: operations["me_api_v1_auth_me_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/chats": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List Chats */
        readonly get: operations["list_chats_api_v1_chats_get"];
        readonly put?: never;
        /** Create Chat */
        readonly post: operations["create_chat_api_v1_chats_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/chats/{chat_id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Chat Detail */
        readonly get: operations["chat_detail_api_v1_chats__chat_id__get"];
        readonly put?: never;
        readonly post?: never;
        /** Delete Chat */
        readonly delete: operations["delete_chat_api_v1_chats__chat_id__delete"];
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/chats/{chat_id}/messages": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Send Message */
        readonly post: operations["send_message_api_v1_chats__chat_id__messages_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/health/live": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Liveness */
        readonly get: operations["health_live"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/health/ready": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Readiness */
        readonly get: operations["health_ready"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/materials": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Materials List */
        readonly get: operations["materials_list_api_v1_materials_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/materials/{revision_id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Material Detail */
        readonly get: operations["material_detail_api_v1_materials__revision_id__get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/materials/{revision_id}/original": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Material Original */
        readonly get: operations["material_original_api_v1_materials__revision_id__original_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountView */
        readonly AccountView: {
            /** Id */
            readonly id: string;
            readonly role: components["schemas"]["Role"];
            /** Username */
            readonly username: string;
        };
        /** AdminRevisionView */
        readonly AdminRevisionView: {
            /** Creator */
            readonly creator: string | null;
            /** Decision */
            readonly decision: string | null;
            /** Description */
            readonly description?: string | null;
            /** Error Code */
            readonly error_code: string | null;
            /** Media Type */
            readonly media_type: string;
            /** Origin Url */
            readonly origin_url: string;
            /** Original Available */
            readonly original_available: boolean;
            /** People */
            readonly people?: string | null;
            /** Period */
            readonly period?: string | null;
            /** Region */
            readonly region?: string | null;
            /**
             * Revision Id
             * Format: uuid
             */
            readonly revision_id: string;
            /** Rights Usage Note */
            readonly rights_usage_note: string | null;
            /** Segments */
            readonly segments: readonly components["schemas"]["SegmentView"][];
            /** Sha256 */
            readonly sha256: string;
            /**
             * Source Id
             * Format: uuid
             */
            readonly source_id: string;
            /** Status */
            readonly status: string;
            /** Tags */
            readonly tags: readonly components["schemas"]["TagView"][];
            /** Title */
            readonly title: string;
        };
        /** AdminSourceView */
        readonly AdminSourceView: {
            /** Decision */
            readonly decision: string | null;
            /** Origin Url */
            readonly origin_url: string;
            /**
             * Revision Id
             * Format: uuid
             */
            readonly revision_id: string;
            /**
             * Source Id
             * Format: uuid
             */
            readonly source_id: string;
            /** Status */
            readonly status: string;
            /** Title */
            readonly title: string;
        };
        /** AuthView */
        readonly AuthView: {
            /** Csrf Token */
            readonly csrf_token: string;
            readonly user: components["schemas"]["AccountView"];
        };
        /** Body_upload_source_api_v1_admin_sources_post */
        readonly Body_upload_source_api_v1_admin_sources_post: {
            /** Creator */
            readonly creator?: string | null;
            /** Description */
            readonly description?: string | null;
            /** File */
            readonly file: string;
            /** Origin Url */
            readonly origin_url: string;
            /** Rights Note */
            readonly rights_note?: string | null;
            /** Source Id */
            readonly source_id?: string | null;
            /** Tags */
            readonly tags?: readonly string[] | null;
            /** Title */
            readonly title: string;
        };
        /** ChatCitationView */
        readonly ChatCitationView: {
            /** Available */
            readonly available: boolean;
            /** Column End */
            readonly column_end: number | null;
            /** Column Start */
            readonly column_start: number | null;
            /** Page */
            readonly page: number | null;
            /**
             * Revision Id
             * Format: uuid
             */
            readonly revision_id: string;
            /** Row End */
            readonly row_end: number | null;
            /** Row Start */
            readonly row_start: number | null;
            /** Section */
            readonly section: string | null;
            /**
             * Segment Id
             * Format: uuid
             */
            readonly segment_id: string;
            /** Sheet */
            readonly sheet: string | null;
            /** Table */
            readonly table: string | null;
        };
        /** ChatDetailView */
        readonly ChatDetailView: {
            /**
             * Id
             * Format: uuid
             */
            readonly id: string;
            /** Title */
            readonly title: string;
            /** Turns */
            readonly turns: readonly components["schemas"]["ChatTurnView"][];
            /**
             * Updated At
             * Format: date-time
             */
            readonly updated_at: string;
        };
        /** ChatSummaryView */
        readonly ChatSummaryView: {
            /**
             * Id
             * Format: uuid
             */
            readonly id: string;
            /** Title */
            readonly title: string;
            /**
             * Updated At
             * Format: date-time
             */
            readonly updated_at: string;
        };
        /** ChatTurnView */
        readonly ChatTurnView: {
            /** Assistant Text */
            readonly assistant_text: string | null;
            /** Citations */
            readonly citations: readonly components["schemas"]["ChatCitationView"][];
            /** Evidence Status */
            readonly evidence_status: string | null;
            /** Ordinal */
            readonly ordinal: number;
            /**
             * Request Id
             * Format: uuid
             */
            readonly request_id: string;
            /** Status */
            readonly status: string;
            /** User Text */
            readonly user_text: string;
        };
        /** CreateAccountInput */
        readonly CreateAccountInput: {
            /** Password */
            readonly password: string;
            /** @default user */
            readonly role: components["schemas"]["Role"];
            /** Username */
            readonly username: string;
        };
        /** DecisionInput */
        readonly DecisionInput: {
            /** Evidence Url */
            readonly evidence_url: string;
            /**
             * Original File
             * @default false
             */
            readonly original_file: boolean;
            /**
             * Provider Transfer
             * @default false
             */
            readonly provider_transfer: boolean;
            /** Reason */
            readonly reason: string;
            /**
             * Sensitivity Cleared
             * @default false
             */
            readonly sensitivity_cleared: boolean;
            /**
             * User Text
             * @default false
             */
            readonly user_text: boolean;
        };
        /** HTTPValidationError */
        readonly HTTPValidationError: {
            /** Detail */
            readonly detail?: readonly components["schemas"]["ValidationError"][];
        };
        /** IntakeView */
        readonly IntakeView: {
            /**
             * Revision Id
             * Format: uuid
             */
            readonly revision_id: string;
            /**
             * Source Id
             * Format: uuid
             */
            readonly source_id: string;
            /** Status */
            readonly status: string;
        };
        /** LocatorView */
        readonly LocatorView: {
            /** Column End */
            readonly column_end: number | null;
            /** Column Start */
            readonly column_start: number | null;
            /**
             * Kind
             * @enum {string}
             */
            readonly kind: "page" | "table";
            /** Page */
            readonly page: number | null;
            /** Row End */
            readonly row_end: number | null;
            /** Row Start */
            readonly row_start: number | null;
            /** Section */
            readonly section: string | null;
            /** Sheet */
            readonly sheet: string | null;
            /** Table */
            readonly table: string | null;
        };
        /** LoginInput */
        readonly LoginInput: {
            /** Password */
            readonly password: string;
            /** Username */
            readonly username: string;
        };
        /** MaterialDetail */
        readonly MaterialDetail: {
            /** Creator */
            readonly creator: string | null;
            /** Description */
            readonly description?: string | null;
            /** Media Type */
            readonly media_type: string;
            /** Origin Url */
            readonly origin_url: string;
            /** Original Available */
            readonly original_available: boolean;
            /** People */
            readonly people?: string | null;
            /** Period */
            readonly period?: string | null;
            /** Region */
            readonly region?: string | null;
            /**
             * Revision Id
             * Format: uuid
             */
            readonly revision_id: string;
            /** Rights Usage Note */
            readonly rights_usage_note: string | null;
            /** Segments */
            readonly segments: readonly components["schemas"]["SegmentView"][];
            /** Tags */
            readonly tags: readonly components["schemas"]["TagView"][];
            /** Title */
            readonly title: string;
        };
        /** MaterialView */
        readonly MaterialView: {
            /** Creator */
            readonly creator: string | null;
            /** Description */
            readonly description?: string | null;
            /** Media Type */
            readonly media_type: string;
            /** Origin Url */
            readonly origin_url: string;
            /** People */
            readonly people?: string | null;
            /** Period */
            readonly period?: string | null;
            /** Region */
            readonly region?: string | null;
            /**
             * Revision Id
             * Format: uuid
             */
            readonly revision_id: string;
            /** Rights Usage Note */
            readonly rights_usage_note: string | null;
            /** Tags */
            readonly tags: readonly components["schemas"]["TagView"][];
            /** Title */
            readonly title: string;
        };
        /** RevokeInput */
        readonly RevokeInput: {
            /** Reason */
            readonly reason: string;
        };
        /**
         * Role
         * @enum {string}
         */
        readonly Role: "user" | "admin";
        /** SegmentView */
        readonly SegmentView: {
            readonly locator: components["schemas"]["LocatorView"];
            /**
             * Segment Id
             * Format: uuid
             */
            readonly segment_id: string;
            /** Text */
            readonly text: string;
        };
        /** SendInput */
        readonly SendInput: {
            /**
             * Request Id
             * Format: uuid
             */
            readonly request_id: string;
            /** Text */
            readonly text: string;
        };
        /** TagView */
        readonly TagView: {
            /** Kind */
            readonly kind: string;
            /** Value */
            readonly value: string;
        };
        /** ValidationError */
        readonly ValidationError: {
            /** Context */
            readonly ctx?: Record<string, never>;
            /** Input */
            readonly input?: unknown;
            /** Location */
            readonly loc: readonly (string | number)[];
            /** Message */
            readonly msg: string;
            /** Error Type */
            readonly type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readonly create_account_api_v1_admin_accounts_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["CreateAccountInput"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["AccountView"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly admin_revision_api_v1_admin_revisions__revision_id__get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly revision_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["AdminRevisionView"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly approve_revision_api_v1_admin_revisions__revision_id__approve_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly revision_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["DecisionInput"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["AdminRevisionView"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly admin_original_api_v1_admin_revisions__revision_id__original_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly revision_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly retry_revision_api_v1_admin_revisions__revision_id__retry_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly revision_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["AdminRevisionView"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly revoke_revision_api_v1_admin_revisions__revision_id__revoke_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly revision_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["RevokeInput"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["AdminRevisionView"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly admin_sources_api_v1_admin_sources_get: {
        readonly parameters: {
            readonly query?: {
                readonly decision?: ("approve" | "revoke" | "none") | null;
                readonly limit?: number;
                readonly media_type?: ("application/pdf" | "text/csv") | null;
                readonly q?: string | null;
                readonly status?: ("candidate" | "processing" | "review_pending" | "failed") | null;
                readonly tag_kind?: ("region" | "people" | "period" | "topic" | "sensitivity") | null;
                readonly tag_value?: string | null;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["AdminSourceView"][];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly upload_source_api_v1_admin_sources_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "multipart/form-data": components["schemas"]["Body_upload_source_api_v1_admin_sources_post"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["IntakeView"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly login_api_v1_auth_login_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["LoginInput"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["AuthView"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly logout_api_v1_auth_logout_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly me_api_v1_auth_me_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["AuthView"];
                };
            };
        };
    };
    readonly list_chats_api_v1_chats_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["ChatSummaryView"][];
                };
            };
        };
    };
    readonly create_chat_api_v1_chats_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ChatSummaryView"];
                };
            };
        };
    };
    readonly chat_detail_api_v1_chats__chat_id__get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly chat_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ChatDetailView"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly delete_chat_api_v1_chats__chat_id__delete: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly chat_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly send_message_api_v1_chats__chat_id__messages_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly chat_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["SendInput"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ChatTurnView"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly health_live: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly [key: string]: string;
                    };
                };
            };
        };
    };
    readonly health_ready: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly [key: string]: string;
                    };
                };
            };
        };
    };
    readonly materials_list_api_v1_materials_get: {
        readonly parameters: {
            readonly query?: {
                readonly media_type?: ("application/pdf" | "text/csv") | null;
                readonly people?: string | null;
                readonly period?: string | null;
                readonly q?: string | null;
                readonly region?: string | null;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["MaterialView"][];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly material_detail_api_v1_materials__revision_id__get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly revision_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["MaterialDetail"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly material_original_api_v1_materials__revision_id__original_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly revision_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/pdf": string;
                    readonly "text/csv": string;
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
