"""source_corpus

Revision ID: 7812c007c854
Revises: 0001_initial
Create Date: 2026-09-30 00:31:57.914180
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "7812c007c854"
down_revision: str | None = "0001_initial"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("origin_url", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
    )
    op.create_table(
        "source_revisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("media_type", sa.String(length=100), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("creator", sa.Text(), nullable=True),
        sa.Column("language", sa.String(length=35), nullable=True),
        sa.Column("period_note", sa.Text(), nullable=True),
        sa.Column("rights_note", sa.Text(), nullable=True),
        sa.Column("captured_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("byte_size > 0", name=op.f("ck_source_revisions_positive_byte_size")),
        sa.CheckConstraint("length(sha256) = 64", name=op.f("ck_source_revisions_sha256_length")),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_source_revisions_source_id_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_revisions")),
        sa.UniqueConstraint("source_id", "sha256", name="uq_source_revisions_source_hash"),
        sa.UniqueConstraint("storage_key", name="uq_source_revisions_storage_key"),
    )
    op.create_table(
        "source_decisions",
        sa.Column("event_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("revision_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("reviewer_id", sa.String(length=100), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("evidence_url", sa.Text(), nullable=False),
        sa.Column("user_text", sa.Boolean(), nullable=False),
        sa.Column("original_file", sa.Boolean(), nullable=False),
        sa.Column("provider_transfer", sa.Boolean(), nullable=False),
        sa.Column("sensitivity_cleared", sa.Boolean(), nullable=False),
        sa.Column("decided_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("kind IN ('approve', 'revoke')", name=op.f("ck_source_decisions_kind")),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["source_revisions.id"],
            name=op.f("fk_source_decisions_revision_id_source_revisions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_source_decisions")),
    )
    op.create_index(
        "ix_source_decisions_revision_event",
        "source_decisions",
        ["revision_id", "event_id"],
        unique=False,
    )
    op.create_table(
        "source_segments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("revision_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("page", sa.Integer(), nullable=True),
        sa.Column("section", sa.Text(), nullable=True),
        sa.Column("sheet", sa.Text(), nullable=True),
        sa.Column("table_name", sa.Text(), nullable=True),
        sa.Column("row_start", sa.Integer(), nullable=True),
        sa.Column("row_end", sa.Integer(), nullable=True),
        sa.Column("column_start", sa.Integer(), nullable=True),
        sa.Column("column_end", sa.Integer(), nullable=True),
        sa.CheckConstraint("kind IN ('prose', 'table')", name=op.f("ck_source_segments_kind")),
        sa.CheckConstraint(
            "(row_start IS NULL AND row_end IS NULL AND "
            "column_start IS NULL AND column_end IS NULL) "
            "OR (row_start IS NOT NULL AND row_end IS NOT NULL "
            "AND column_start IS NOT NULL AND column_end IS NOT NULL "
            "AND (sheet IS NOT NULL OR table_name IS NOT NULL))",
            name=op.f("ck_source_segments_table_range_complete"),
        ),
        sa.CheckConstraint(
            "column_end IS NULL OR column_end >= column_start",
            name=op.f("ck_source_segments_column_end"),
        ),
        sa.CheckConstraint(
            "column_start IS NULL OR column_start >= 1",
            name=op.f("ck_source_segments_column_start"),
        ),
        sa.CheckConstraint("ordinal >= 0", name=op.f("ck_source_segments_ordinal")),
        sa.CheckConstraint(
            "page IS NOT NULL OR row_start IS NOT NULL", name=op.f("ck_source_segments_has_locator")
        ),
        sa.CheckConstraint("page IS NULL OR page >= 1", name=op.f("ck_source_segments_page")),
        sa.CheckConstraint(
            "row_end IS NULL OR row_end >= row_start", name=op.f("ck_source_segments_row_end")
        ),
        sa.CheckConstraint(
            "row_start IS NULL OR row_start >= 1", name=op.f("ck_source_segments_row_start")
        ),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["source_revisions.id"],
            name=op.f("fk_source_segments_revision_id_source_revisions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_segments")),
        sa.UniqueConstraint("revision_id", "ordinal", name="uq_source_segments_revision_ordinal"),
    )
    op.create_index(
        "ix_source_segments_revision_page", "source_segments", ["revision_id", "page"], unique=False
    )
    op.create_table(
        "source_tags",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("revision_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "kind IN ('region', 'people', 'period', 'topic', 'sensitivity')",
            name=op.f("ck_source_tags_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["source_revisions.id"],
            name=op.f("fk_source_tags_revision_id_source_revisions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_tags")),
        sa.UniqueConstraint(
            "revision_id", "kind", "value", name="uq_source_tags_revision_kind_value"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("source_tags")
    op.drop_index("ix_source_segments_revision_page", table_name="source_segments")
    op.drop_table("source_segments")
    op.drop_index("ix_source_decisions_revision_event", table_name="source_decisions")
    op.drop_table("source_decisions")
    op.drop_table("source_revisions")
    op.drop_table("sources")
    # ### end Alembic commands ###
