"""source_processing

Revision ID: df612efc24ce
Revises: e425fb4d6c5e
Create Date: 2026-09-30 08:39:05.650226
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "df612efc24ce"
down_revision: str | None = "e425fb4d6c5e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source_processing",
        sa.Column("revision_id", sa.Uuid(), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state IN ('candidate', 'processing', 'review_pending', 'failed')",
            name=op.f("ck_source_processing_state"),
        ),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["source_revisions.id"],
            name=op.f("fk_source_processing_revision_id_source_revisions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("revision_id", name=op.f("pk_source_processing")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("source_processing")
    # ### end Alembic commands ###
